from for_all import for_all
from basic_checks import should_till
final_plot = [
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
[Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush],
[Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree, Entities.Bush, Entities.Tree],
]

def check_and_harvest():
	pos_x = get_pos_x()
	pos_y = get_pos_y()
	
	curr_plant = final_plot[pos_y][pos_x]
	
	if can_harvest():
		harvest()
		#should_till(Entities.Carrot)
		plant(curr_plant)
		#plant(Entities.Carrot)

def water():
	use_item(Items.Water)
	
#for _ in range(10):
	#for_all(water)

while True:
	for_all(check_and_harvest)


